---
title: "Update on Markov models #2"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### July 8, 2016

```{r, message=FALSE, warning=FALSE, include=FALSE}

setwd("/Users/lesliehuang/Dropbox/MA-thesis-analysis/")

set.seed(1234)

libraries <- c("foreign", "utils", "stargazer", "dplyr", "devtools", "quanteda", "quantedaData", "ggplot2", "stringr", "LIWCalike", "topicmodels", "lda", "stm", "LDAvis", "austin", "forecast", "lmtest", "strucchange", "vars", "tseries", "urca", "HMM", "msm", "depmixS4")
lapply(libraries, require, character.only=TRUE)

# get LIWC dict
spanish_dict <- dictionary(file = "../LIWC/Spanish_LIWC2007_Dictionary.dic", format = "LIWC")

################################################################################## 
################################################################################## 
# get monthly levels of violence
monthly_viol <- read.csv("../MA-datasets/violence_stats.csv", stringsAsFactors = FALSE)
monthly_viol$date <- as.Date(as.yearmon(monthly_viol$date, "%Y-%m"))
monthly_viol[,2:4] <- sapply(monthly_viol[,2:4], function(x) { as.numeric(x)})
monthly_viol <- subset(monthly_viol, select = c(2:4, 1))

# some major dates for plotting
major_violence <- as.Date(c("7/20/13", "1/16/13", "7/29/14", "11/16/14", "4/15/15", "5/31/15", "6/15/15", "6/22/15"), "%m/%d/%y")
major_agree <- as.Date(c("8/26/12", "5/26/13", "11/6/13", "5/16/14", "3/7/15", "6/2/15", "9/23/15"), "%m/%d/%y")

cf_start <- as.Date(c("11/20/12", "12/15/13", "5/16/14", "12/20/14", "7/20/15"), "%m/%d/%y")
cf_end <- as.Date(c("1/20/13", "1/15/14", "5/28/14", "5/22/15", "1/1/16"), "%m/%d/%y")
ceasefires <- data.frame(start = as.Date(c("11/20/12", "12/15/13", "5/16/14", "12/20/14", "7/20/15"), "%m/%d/%y"), end = as.Date(c("1/20/13", "1/15/14", "5/28/14", "5/22/15", "1/1/16"), "%m/%d/%y"))

# df of all dates
dates <- rbind(data.frame(date = major_violence, group = "major_viol"), data.frame(date = major_agree, group = "major_agree"), data.frame(date = cf_start, group = "ceasefire_start"), data.frame(date = cf_end, group = "ceasefire_end"))
dates <- arrange(dates, date)

################################################################################## 
# Some functions to extract sentiment, loess it, and return results

# Function to get raw LIWC measures
liwc_extractor <- function(df) {
  # run liwc
  liwc_results <- liwcalike(df$text, spanish_dict)
  
  # get date metadata
  df_dates <- dplyr::select(df, date)
  date <- as.Date(df_dates[[1]], "%Y-%m-%d")
  
  # extract the measures we want
  liwc_results <- dplyr::select(liwc_results, EmoNeg, EmoPos, Ellos, Muerte)
  
  # make the dataframe
  results_df <- data.frame(cbind(sapply(liwc_results, function(x) {as.numeric(x)})))
  results_df$date <- as.Date(date, "%Y-%m-%d")
  return(results_df)
}

# Function to take a df of raw LIWC values and return loessed values
liwc_loess <- function(liwc_results) {
  date <- as.Date(liwc_results$date, origin = "1970-01-01")
  results_df <- data.frame(cbind(sapply(liwc_results[,1:4], function(x) { loess(x ~ as.numeric(liwc_results$date), control = loess.control(surface = "direct"))$y})))
  results_df$date <- date
  return(results_df)
}

# Function to return loess predictions as a list
loess_lines <- function(liwc_results) {
  
  list_models <- list(sapply(liwc_results[,1:4], function(x) {loess(x ~ as.numeric(liwc_results$date), control=loess.control(surface="direct"))}))
  return(list_models)
}

#################################################################################
# import FARC communiques
FARC <- read.csv("../MA-datasets/FARC_communiques.csv", stringsAsFactors = FALSE)

# raw LIWC measures
FARC_raw <- liwc_extractor(FARC)

# loess it
FARC_results <- liwc_loess(FARC_raw)

# get the loess lines for plotting
FARC_lines <- loess_lines(FARC_raw)

#################################################################################
# do the same for joint communiques
joint <- read.csv("../MA-datasets/jointstatements.csv", stringsAsFactors = FALSE)
# delete some empty documents
joint <- filter(joint, text != "")
joint <- slice(joint, -19)

# LIWC estimates
joint_raw <- liwc_extractor(joint)

# loessed point estimates
joint_results <- liwc_loess(joint_raw)

# get the loess lines for plotting
joint_lines <- loess_lines(joint_raw)

#################################################################################
# and the same for govt statements
govt <- read.csv("govtstatements.csv", stringsAsFactors = FALSE)

# LIWC estimates
govt_raw <- liwc_extractor(govt)

# loessed point estimates
govt_results <- liwc_loess(govt_raw)

# get the loess lines for plotting
govt_lines <- loess_lines(govt_raw)


# stuff needed to make this run
forms <- list(FARC_results$EmoNeg ~ 1, FARC_results$EmoPos ~ 1, FARC_results$Ellos ~ 1)
FARC_results1 <- FARC_results[, -4]
FARC_results1 <- filter(FARC_results1, date >= "2012-01-01")

# Introducing... public opinion
public_op <- read.csv("../MA-datasets/public opinion.csv", stringsAsFactors = FALSE)

public_op <- public_op[,1:3]
public_op$date <- as.Date(as.yearmon(public_op$date, "%Y-%m"))
public_op[,2:3] <- sapply(public_op[,2:3], function(x) { as.numeric(x)})
public_op <- subset(public_op, select = c(2:3, 1))
public_op <- na.omit(public_op)
```

### What's the optimal number of latent states?
```{r, echo = TRUE, message = FALSE, warning = FALSE}
# Let's test n = 2:10
num_states <- seq(2, 10, by = 1)

# formulas
forms1 <- list(FARC_results1$EmoNeg ~ 1, FARC_results1$EmoPos ~ 1, FARC_results1$Ellos ~ 1)

# Find the BIC values
BIC_vals <- sapply(num_states, function(x) {BIC(depmix(forms1, family = list(gaussian(), gaussian(), gaussian()), nstates = x, data = FARC_results1))})

BIC_df <- data.frame(cbind(num_states, BIC_vals))

# and plot them
BIC_plot <- ggplot(BIC_df, aes(x = num_states, y = BIC_vals)) +
  geom_point() +
  ggtitle("BIC Values for n = 2:10 Latent States HMM")

BIC_plot
```

```{r, message=FALSE, warning=FALSE, include=FALSE}
# Function takes 1 parameter: a dataframe, and returns one parameter: a dataframe
add_monthlies <- function(df) {
  dates <- df["date"]
  
  # add columns for the monthly data we're adding
  col_names <- c("FARC_actions", "army_casualties", "pres_approve", "peace_approve")
  df[, col_names] <- NA
  for (i in 1:length(dates[[1]])) {
    date <- dates[i, 1]
    year <- format(date, "%Y")
    month <- format(date, "%m")
    
    monthly_date <- as.Date(paste(year, month, "01", sep = "-"))
    
    # get the stats from violence and opinion dfs
    viol <- filter(monthly_viol, date == monthly_date)
    public <- filter(public_op, date == monthly_date)
    
    # write them to new df
    df["FARC_actions"][i, 1] <- as.numeric(viol[1])
    df["army_casualties"][i, 1] <- as.numeric(viol[2])
    df["pres_approve"][i, 1] <- as.numeric(public[1])
    df["peace_approve"][i, 1] <- as.numeric(public[2])
  }
  
  return(df)
}

# run to add violence/public opinion levels to FARC df
FARC_results2 <- add_monthlies(FARC_results1)
```

### BIC and AIC with model fitting and covariates included


### Here's the data with covariates (2 violence and 2 public opinion) added
```{r, echo=TRUE, message=FALSE, warning=FALSE}
head(FARC_results2)

# new formulas
forms2 <- list(FARC_results2$EmoNeg ~ 1, FARC_results2$EmoPos ~ 1, FARC_results2$Ellos ~ 1)
```

### BIC values
```{r, echo=TRUE, message=FALSE, warning=FALSE}
# what are BIC values of the fitted models?
BIC_vals2 <- sapply(num_states, function(x) {BIC(fit(depmix(forms2, family = list(gaussian(), gaussian(), gaussian()), nstates = x, data = FARC_results2[,-(6:9)], transitions = list(~ FARC_actions, ~ army_casualties, ~ pres_approve, ~ peace_approve))))})

BIC_df2 <- data.frame(cbind(num_states, BIC_vals2))

# plot the BIC values to select the optimal number of states
BIC_plot2 <- ggplot(BIC_df2, aes(x = num_states, y = BIC_vals2)) +
  geom_point() +
  ggtitle("BIC Values for n = 2:10 Latent States Fitted HMM w/ Covariates")

BIC_plot2
```

### AIC values
```{r, echo=TRUE, message=FALSE, warning=FALSE}

# what are AIC values of the fitted models?
AIC_vals <- sapply(num_states, function(x) {AIC(fit(depmix(forms2, family = list(gaussian(), gaussian(), gaussian()), nstates = x, data = FARC_results2[,-(6:9)], transitions = list(~ FARC_actions, ~ army_casualties, ~ pres_approve, ~ peace_approve))))})

AIC_df <- data.frame(cbind(num_states, AIC_vals))

# plot the BIC values to select the optimal number of states
AIC_plot <- ggplot(AIC_df, aes(x = num_states, y = AIC_vals)) +
  geom_point() +
  ggtitle("AIC Values for n = 2:10 Latent States Fitted HMM w/ Covariates")


AIC_plot
```

### Using depmixS4() to find transition matrix for n = 3
```{r, echo=TRUE, message=FALSE, warning=FALSE}

# Hidden Markov model with 3 states
mod <- depmix(forms2, family = list(gaussian(), gaussian(), gaussian()), nstates = 3, data = FARC_results2[,-(6:9)], transitions = list(~ FARC_actions, ~ army_casualties, ~ pres_approve, ~ peace_approve))

mod

hmm_mod <- fit(mod)

summary(hmm_mod)

head(posterior(hmm_mod))
```
