---
title: "Update: Markov Models, PCA"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### July 12, 2016

```{r, message=FALSE, warning=FALSE, include=FALSE}
setwd("/Users/lesliehuang/Dropbox/MA-thesis-analysis/")

set.seed(1234)

libraries <- c("foreign", "utils", "stargazer", "dplyr", "devtools", "quanteda", "ggplot2", "stringr", "LIWCalike", "austin", "forecast", "lmtest", "strucchange", "vars", "tseries", "urca", "depmixS4", "rrcov", "MCMCglmm")
lapply(libraries, require, character.only=TRUE)

# get LIWC dict
spanish_dict <- dictionary(file = "../LIWC/Spanish_LIWC2007_Dictionary.dic", format = "LIWC")

################################################################################## 
################################################################################## 
# get monthly levels of violence
monthly_viol <- read.csv("../MA-datasets/violence_stats.csv", stringsAsFactors = FALSE)
monthly_viol$date <- as.Date(as.yearmon(monthly_viol$date, "%Y-%m"))
monthly_viol[,2:4] <- sapply(monthly_viol[,2:4], function(x) { as.numeric(x)})
monthly_viol <- subset(monthly_viol, select = c(2:4, 1))

# some major dates for plotting
major_violence <- as.Date(c("7/20/13", "1/16/13", "7/29/14", "11/16/14", "4/15/15", "5/31/15", "6/15/15", "6/22/15"), "%m/%d/%y")
major_agree <- as.Date(c("8/26/12", "5/26/13", "11/6/13", "5/16/14", "3/7/15", "6/2/15", "9/23/15"), "%m/%d/%y")

cf_start <- as.Date(c("11/20/12", "12/15/13", "5/16/14", "12/20/14", "7/20/15"), "%m/%d/%y")
cf_end <- as.Date(c("1/20/13", "1/15/14", "5/28/14", "5/22/15", "1/1/16"), "%m/%d/%y")
ceasefires <- data.frame(start = as.Date(c("11/20/12", "12/15/13", "5/16/14", "12/20/14", "7/20/15"), "%m/%d/%y"), end = as.Date(c("1/20/13", "1/15/14", "5/28/14", "5/22/15", "1/1/16"), "%m/%d/%y"))

# df of all dates
dates <- rbind(data.frame(date = major_violence, group = "major_viol"), data.frame(date = major_agree, group = "major_agree"), data.frame(date = cf_start, group = "ceasefire_start"), data.frame(date = cf_end, group = "ceasefire_end"))
dates <- arrange(dates, date)

################################################################################## 
# Some functions to extract sentiment, loess it, and return results

# Function to get raw LIWC measures
liwc_extractor <- function(df) {
  # run liwc
  liwc_results <- liwcalike(df$text, spanish_dict)
  
  # get date metadata
  df_dates <- dplyr::select(df, date)
  date <- as.Date(df_dates[[1]], "%Y-%m-%d")
  
  # extract the measures we want
  liwc_results <- dplyr::select(liwc_results, EmoNeg, EmoPos, Ellos, Muerte)
  
  # make the dataframe
  results_df <- data.frame(cbind(sapply(liwc_results, function(x) {as.numeric(x)})))
  results_df$date <- as.Date(date, "%Y-%m-%d")
  return(results_df)
}

# Function to take a df of raw LIWC values and return loessed values
liwc_loess <- function(liwc_results) {
  date <- as.Date(liwc_results$date, origin = "1970-01-01")
  results_df <- data.frame(cbind(sapply(liwc_results[,1:4], function(x) { loess(x ~ as.numeric(liwc_results$date), control = loess.control(surface = "direct"))$y})))
  results_df$date <- date
  return(results_df)
}

# Function to return loess predictions as a list
loess_lines <- function(liwc_results) {
  
  list_models <- list(sapply(liwc_results[,1:4], function(x) {loess(x ~ as.numeric(liwc_results$date), control=loess.control(surface="direct"))}))
  return(list_models)
}

#################################################################################
# import FARC communiques
FARC <- read.csv("../MA-datasets/FARC_communiques.csv", stringsAsFactors = FALSE)

# raw LIWC measures
FARC_raw <- liwc_extractor(FARC)

# loess it
FARC_results <- liwc_loess(FARC_raw)

# get the loess lines for plotting
FARC_lines <- loess_lines(FARC_raw)

#################################################################################
# do the same for joint communiques
joint <- read.csv("../MA-datasets/jointstatements.csv", stringsAsFactors = FALSE)
# delete some empty documents
joint <- filter(joint, text != "")
joint <- slice(joint, -19)

# LIWC estimates
joint_raw <- liwc_extractor(joint)

# loessed point estimates
joint_results <- liwc_loess(joint_raw)

# get the loess lines for plotting
joint_lines <- loess_lines(joint_raw)

#################################################################################
# and the same for govt statements
govt <- read.csv("govtstatements.csv", stringsAsFactors = FALSE)

# LIWC estimates
govt_raw <- liwc_extractor(govt)

# loessed point estimates
govt_results <- liwc_loess(govt_raw)

# get the loess lines for plotting
govt_lines <- loess_lines(govt_raw)


# stuff needed to make this run
forms <- list(FARC_results$EmoNeg ~ 1, FARC_results$EmoPos ~ 1, FARC_results$Ellos ~ 1)
FARC_results1 <- FARC_results[, -4]
FARC_results1 <- filter(FARC_results1, date >= "2012-01-01")

# Introducing... public opinion
public_op <- read.csv("../MA-datasets/public opinion.csv", stringsAsFactors = FALSE)

public_op <- public_op[,1:3]
public_op$date <- as.Date(as.yearmon(public_op$date, "%Y-%m"))
public_op[,2:3] <- sapply(public_op[,2:3], function(x) { as.numeric(x)})
public_op <- subset(public_op, select = c(2:3, 1))
public_op <- na.omit(public_op)
```

## PCA

### Take 1
```{r, message=FALSE, warning=FALSE, include=FALSE}
# make corpus of FARC and government statements
FARC_corpus <- corpus(FARC$text, docvars = FARC_results$dates)
govt_corpus <- corpus(govt$text, docvars = govt_results$dates)
all_corpora <- FARC_corpus + govt_corpus

# Metadata for later: "side" and dates
sides <- c(rep("FARC", length(FARC_corpus[, 1])), rep("govt", length(govt_corpus[, 1])))
pca_dates <- c(FARC_results$date, govt_results$date)

# make dfm
all_dfm <- dfm(all_corpora, language = "spanish", stem = TRUE, ignoredFeatures = stopwords("spanish"))

# run PCA
statements_PCA <- prcomp(all_dfm, center = TRUE, scale. = TRUE)
```

```{r, echo=TRUE, message=FALSE, warning=FALSE}
summary(statements_PCA)

# plot it
plot(statements_PCA, type = "l", main="PCA of FARC and Govt Statements")
# first 2 PCs account for ~10% of variance. Could be better...
```

```{r, message=FALSE, warning=FALSE, include=FALSE}
### Graph PC1 as a time series:

# make df of PC1 values, date, and side
statements_PC1_2 <- data.frame(statements_PCA$x[1:length(statements_PCA$x[,1]),1:2])
statements_PC1_2["date"] <- pca_dates
statements_PC1_2["side"] <- sides
colnames(statements_PC1_2) <- c("PC1", "PC2", "date", "side")

PC1_gg <- ggplot(filter(statements_PC1_2, side == "FARC"), aes(x = as.Date(date, origin = "1970-01-01"), y = PC1, color = "FARC")) +
  geom_jitter() +
  geom_point(data = filter(statements_PC1_2, side == "govt"), aes(x = as.Date(date, origin = "1970-01-01"), y = PC1, color = "Govt")) +
  ggtitle("Plot of First Principal Components over Time") +
  scale_x_date(date_minor_breaks = "1 month",
               limits = c(as.Date("2012-06-01", "%Y-%m-%d"), NA))

# Graph PC2
# collect date and side metadata with PC1 values
PC2_gg <- ggplot(filter(statements_PC1_2, side == "FARC"), aes(x = as.Date(date, origin = "1970-01-01"), y = PC2, color = "FARC")) +
  geom_jitter() +
  geom_point(data = filter(statements_PC1_2, side == "govt"), aes(x = as.Date(date, origin = "1970-01-01"), y = PC2, color = "Govt")) +
  ggtitle("Plot of Second Principal Components over Time") +
  scale_x_date(date_minor_breaks = "1 month",
               limits = c(as.Date("2012-06-01", "%Y-%m-%d"), NA))
```

### Time series plot of the first two PCs
```{r, echo=FALSE, message=FALSE, warning=FALSE}
PC1_gg
PC2_gg
```

### Take 2: Re-run PCA after removing outlier, applying log transformation
```{r, message=FALSE, warning=FALSE, include=FALSE}
FARC_corpus_trimmed <- corpus(FARC$text[-94], docvars = FARC_results$dates[-94])
all_corpora_trimmed <- FARC_corpus_trimmed + govt_corpus
all_dfm_trimmed <- dfm(all_corpora_trimmed, language = "spanish", stem = TRUE, ignoredFeatures = stopwords("spanish"))
statements_PCA_trimmed <- prcomp(all_dfm_trimmed, center = TRUE, scale. = TRUE)
```

### Graph time series of the first two PCs with outlier removed and log transformation
```{r, message=FALSE, warning=FALSE, include=FALSE}
FARC_corpus_trimmed <- corpus(FARC$text[-94], docvars = FARC_results$dates[-94])
all_corpora_trimmed <- FARC_corpus_trimmed + govt_corpus
all_dfm_trimmed <- dfm(all_corpora_trimmed, language = "spanish", stem = TRUE, ignoredFeatures = stopwords("spanish"))
statements_PCA_trimmed <- prcomp(all_dfm_trimmed, center = TRUE, scale. = TRUE)

statements_PC1_2_trimmed <- data.frame(statements_PCA_trimmed$x[1:length(statements_PCA_trimmed$x[,1]),1:2])
statements_PC1_2_trimmed["date"] <- pca_dates[-94]
statements_PC1_2_trimmed["side"] <- sides[-94]
colnames(statements_PC1_2_trimmed) <- c("PC1", "PC2", "date", "side")

# Plot PC1 time series
PC1_gg_trimmed <- ggplot(filter(statements_PC1_2_trimmed, side == "FARC"), aes(x = as.Date(date, origin = "1970-01-01"), y = PC1, color = "FARC")) +
  geom_smooth(method = "loess", se = FALSE) +
  geom_jitter() +
  geom_point(data = filter(statements_PC1_2_trimmed, side == "govt"), aes(x = as.Date(date, origin = "1970-01-01"), y = PC1, color = "Govt")) +
  geom_smooth(method = "loess", se = FALSE, data = statements_PC1_2_trimmed, aes(x = as.Date(date, origin = "1970-01-01"), y = PC1, color = "Govt")) +
  ggtitle("Plot of First Principal Components over Time (Outlier Removed)") +
  scale_x_date(date_minor_breaks = "1 month",
               limits = c(as.Date("2012-06-01", "%Y-%m-%d"), NA)) +
  labs(
    x = "Date",
    y = "PC1",
    color = "Legend")

# Graph PC2
# collect date and side metadata with PC1 values
PC2_gg_trimmed <- ggplot(filter(statements_PC1_2_trimmed, side == "FARC"), aes(x = as.Date(date, origin = "1970-01-01"), y = PC2, color = "FARC")) +
  geom_smooth(method = "loess", se = FALSE) +
  geom_jitter() +
  geom_point(data = filter(statements_PC1_2_trimmed, side == "govt"), aes(x = as.Date(date, origin = "1970-01-01"), y = PC2, color = "Govt")) +
  geom_smooth(method = "loess", se = FALSE, data = statements_PC1_2_trimmed, aes(x = as.Date(date, origin = "1970-01-01"), y = PC2, color = "Govt")) +
  ggtitle("Plot of Second Principal Components over Time (Outlier Removed)") +
  scale_x_date(date_minor_breaks = "1 month",
               limits = c(as.Date("2012-06-01", "%Y-%m-%d"), NA)) +
  labs(
    x = "Date",
    y = "PC2",
    color = "Legend")
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
summary(statements_PCA_trimmed)
plot(statements_PCA_trimmed, type = "l", main="PCA of FARC and Govt Statements")
PC1_gg_trimmed
PC2_gg_trimmed
```

### Take 3: Robust PCA from rrcov()
```{r, echo=TRUE, message=FALSE, warning=FALSE}
# Robust PCA
rob_pca <- PcaHubert(all_dfm)
# First 2 components account for 65% of variance
print(rob_pca)
summary(rob_pca)

# plot
screeplot(rob_pca, type = "lines", main = "Robust PCA with 10 Components")
```

```{r, message=FALSE, warning=FALSE, include=FALSE}
# let's plot the time series of PC1
rob_pc1 <- data.frame(rob_pca@scores)
rob_pc1 <- dplyr::select(rob_pc1, PC1)
rob_pc1["side"] <- sides
rob_pc1["date"] <- pca_dates

# Robust PC1 graph
PC1_gg_robust <- ggplot(filter(rob_pc1, side == "FARC"), aes(x = as.Date(date, origin = "1970-01-01"), y = PC1, color = "FARC")) +
  geom_smooth(method = "loess", se = FALSE) +
  geom_jitter() +
  geom_point(data = filter(rob_pc1, side == "govt"), aes(x = as.Date(date, origin = "1970-01-01"), y = PC1, color = "Govt")) +
  geom_smooth(method = "loess", se = FALSE, data = rob_pc1, aes(x = as.Date(date, origin = "1970-01-01"), y = PC1, color = "Govt")) +
  ggtitle("Plot of First Principal Components over Time (Robust PCA)") +
  scale_x_date(date_minor_breaks = "1 month",
               limits = c(as.Date("2012-06-01", "%Y-%m-%d"), NA)) + 
  labs(
    x = "Date",
    y = "PC1",
    color = "Legend")
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
PC1_gg_robust
```

## MCMC for sentiment responsiveness
```{r, message=FALSE, warning=FALSE, include=FALSE}
# Transition model: sentiment-responds-to-sentiment

# Classify overall sentiment as "high" or "low": Compare negative and positive emotion proportions within a given document. 1 = high, 0 = low
FARC_results3 <- FARC_results
FARC_results3["sentiment_level"] <- as.numeric(2 * FARC_results3$EmoNeg <= FARC_results3$EmoPos)
FARC_results3["side"] <- "FARC"
govt_results3 <- govt_results
govt_results3["side"] <- "govt"
govt_results3["sentiment_level"] <- as.numeric(2 * govt_results3$EmoNeg <= govt_results3$EmoPos)

# combine them into one stream
transition_chain <- rbind(FARC_results3, govt_results3)
# and sort by date
transition_chain <- transition_chain[order(as.Date(transition_chain$date, format = "%Y-%m-%d")), ]
# and filter to the peace process
transition_chain <- filter(transition_chain, date > "2012-01-01")

# pairwise comparison to gauge "responsiveness": how often are the parties giving statements at t and t-1 different?

get_responsiveness <- function(df) {
  # put boolean of pairwise comparisons here
  vect <- rep(NA, (length(df[ , 1]) - 1))
  
  for (i in 2:length(df[ , 1])) {
    side_t <- df["side"][i, ]
    side_t_1 <- df["side"][i-1, ]
    
    vect[i] <- side_t != side_t_1
  }
  
  return(vect)
}

# how frequent are "responding pairs"?
pairwise_responsiveness <- get_responsiveness(transition_chain)
pairwise_num <- sum(na.omit(as.numeric(pairwise_responsiveness)))
pairwise_num

# Make the MCMC matrix
mc_mat <- dplyr::select(transition_chain, date, sentiment_level, side)

# Set up x = current state, y = next state.
# State1 = FARC-low, State 2 = FARC-high, State 3 = govt-low, State 4 = govt-high
# Function takes 1 parameter: a df with "side" and "sentiment_level" variables
state_maker <- function(df) {
  df["state_x"] <- NA
  
  # fill in the appropriate states
  for (i in 1:length(df[, 1])) {
    
    # Divide FARC into states 1 and 2
    if (df["side"][i, ] == "FARC") {
      
      if (df["sentiment_level"][i, ] == 0) {
        df["state_x"][i, ] <- 1
      }
      
      else {
        df["state_x"][i, ] <- 2
      }
    }
    
    # Divide govt into states 3 and 4
    if (df["side"][i, ] == "govt") {
      
      if (df["sentiment_level"][i, ] == 0) {
      df["state_x"][i, ] <- 3
      }
      
    else {
      df["state_x"][i, ] <- 4
    }
      
  }
  }
  
  df["state_y"] <- NA
  
  for (i in 1:length(df[, 1]) -1) {
    df["state_y"][i, ] <- df["state_x"][i+1, ]
  }
  
  return(df)
  }

mc_mat <- state_maker(mc_mat)
# add violence and public opinion for random effects
# Function takes 1 parameter: a dataframe, and returns one parameter: a dataframe
add_monthlies <- function(df) {
  dates <- df["date"]
  
  # add columns for the monthly data we're adding
  col_names <- c("FARC_actions", "army_casualties", "pres_approve", "peace_approve")
  df[, col_names] <- NA
  for (i in 1:length(dates[[1]])) {
    date <- dates[i, 1]
    year <- format(date, "%Y")
    month <- format(date, "%m")
    
    monthly_date <- as.Date(paste(year, month, "01", sep = "-"))
    
    # get the stats from violence and opinion dfs
    viol <- filter(monthly_viol, date == monthly_date)
    public <- filter(public_op, date == monthly_date)
    
    # write them to new df
    df["FARC_actions"][i, 1] <- as.numeric(viol[1])
    df["army_casualties"][i, 1] <- as.numeric(viol[2])
    df["pres_approve"][i, 1] <- as.numeric(public[1])
    df["peace_approve"][i, 1] <- as.numeric(public[2])
  }
  
  return(df)
}



mc_mat <- add_monthlies(mc_mat)
```

### Let's have a look at the data:
```{r, echo=TRUE, message=FALSE, warning=FALSE}
head(mc_mat)
```

### Run MCMC
```{r, echo=TRUE, fig.height=12, message=FALSE, warning=FALSE}
mc_model <- MCMCglmm(state_y ~ state_x, random = NULL, data = mc_mat, family = "categorical", rcov = ~us(trait):units)
summary(mc_model)
plot(mc_model$VCV)
```